# Generated by Django 5.2.7 on 2025-10-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, unique=True, verbose_name='行业名称')),
                ('industry_code', models.CharField(max_length=50, unique=True, verbose_name='行业代码')),
            ],
            options={
                'verbose_name': '行业信息',
                'verbose_name_plural': '行业信息',
                'db_table': 'industries',
                'indexes': [models.Index(fields=['industry_name'], name='idx_industry_name'), models.Index(fields=['industry_code'], name='idx_industry_code')],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchants_name', models.CharField(max_length=100, verbose_name='商户名称')),
                ('credit_code', models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码')),
                ('license_number', models.CharField(max_length=50, verbose_name='营业执照编号')),
                ('legal_person_name', models.CharField(max_length=50, verbose_name='法人代表姓名')),
                ('legal_person_id', models.CharField(max_length=18, verbose_name='法人代表身份证号')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('establishment_date', models.DateField(verbose_name='成立日期')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.industry', verbose_name='所属行业')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.street', verbose_name='所属街道')),
            ],
            options={
                'verbose_name': '商户信息',
                'verbose_name_plural': '商户信息',
                'db_table': 'merchants',
                'indexes': [models.Index(fields=['credit_code'], name='idx_credit_code'), models.Index(fields=['merchants_name'], name='idx_merchants_name'), models.Index(fields=['license_number'], name='idx_license_number'), models.Index(fields=['legal_person_name'], name='idx_legal_person'), models.Index(fields=['street'], name='idx_streets_id'), models.Index(fields=['industry'], name='idx_industry_id')],
            },
        ),
    ]
