# Generated by Django 5.2.7 on 2025-10-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='权限组名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='权限组描述')),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组',
                'db_table': 'roles',
                'indexes': [models.Index(fields=['name'], name='idx_role_name')],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希值')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, help_text='True表示启用，False表示禁用', verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='admins.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admins',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['username'], name='idx_admin_username'), models.Index(fields=['role'], name='idx_admin_role'), models.Index(fields=['status'], name='idx_admin_status')],
            },
        ),
    ]
