# Generated by Django 5.2.7 on 2025-10-17 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='民族名称')),
            ],
            options={
                'verbose_name': '民族',
                'verbose_name_plural': '民族管理',
                'db_table': 'ethnicities',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='居民姓名')),
                ('id_card', models.CharField(db_index=True, max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('political_affiliation', models.SmallIntegerField(choices=[(0, '群众'), (1, '中共党员'), (2, '共青团员'), (3, '中国国民党革命委员会'), (4, '中国民主同盟'), (5, '中国民主建国会'), (6, '中国民主促进会'), (7, '中国农工民主党'), (8, '中国致公党'), (9, '九三学社'), (10, '台湾民主自治同盟')], default=0, verbose_name='政治面貌')),
                ('household_address', models.CharField(max_length=255, verbose_name='户籍地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系方式')),
                ('marital_status', models.SmallIntegerField(choices=[(0, '未婚'), (1, '已婚'), (2, '离异'), (3, '丧偶')], default=0, verbose_name='婚姻状况')),
                ('education_level', models.SmallIntegerField(choices=[(0, '文盲'), (1, '小学'), (2, '初中'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '研究生')], default=0, verbose_name='学历')),
                ('population_type', models.SmallIntegerField(choices=[(0, '常住人口'), (1, '非常住人口')], default=0, verbose_name='人口类型')),
                ('residential_type', models.SmallIntegerField(choices=[(0, '楼房'), (1, '平房')], default=0, verbose_name='住宅类型')),
                ('own_house', models.SmallIntegerField(choices=[(0, '是'), (1, '否')], default=0, verbose_name='是否自有房')),
                ('is_low_income', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否低保户')),
                ('is_beneficiary', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否五保户')),
                ('is_disabled', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否残疾')),
                ('is_special_support', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否特扶人口')),
                ('is_key_person', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否重点对象')),
                ('is_deceased', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否死亡')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residents.ethnicity', verbose_name='民族')),
            ],
            options={
                'verbose_name': '居民',
                'verbose_name_plural': '居民管理',
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='LowIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_date', models.DateTimeField(verbose_name='认证日期')),
                ('bank_account_number', models.CharField(max_length=50, unique=True, verbose_name='银行卡号（唯一）')),
                ('bank_account_name', models.CharField(max_length=100, verbose_name='银行卡账户名称')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(db_column='resident_id', on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '低保户信息',
                'verbose_name_plural': '低保户信息',
                'db_table': 'low_income',
            },
        ),
        migrations.CreateModel(
            name='FiveGuarantees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='五保户唯一标识')),
                ('authentication_date', models.DateTimeField(verbose_name='认证日期')),
                ('bank_account_number', models.CharField(max_length=50, unique=True, verbose_name='银行卡号（唯一）')),
                ('bank_account_name', models.CharField(max_length=100, verbose_name='银行卡账户名称')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five_guarantees', to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '五保户信息',
                'verbose_name_plural': '五保户信息',
                'db_table': 'five_guarantees',
            },
        ),
        migrations.CreateModel(
            name='Disabled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='残疾人唯一标识')),
                ('authentication_date', models.DateTimeField(verbose_name='认证日期')),
                ('bank_account_number', models.CharField(max_length=50, unique=True, verbose_name='银行卡号（唯一）')),
                ('bank_account_name', models.CharField(max_length=100, verbose_name='银行卡账户名称')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled', to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '残疾人信息',
                'verbose_name_plural': '残疾人信息',
                'db_table': 'disabled',
            },
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='死亡户唯一标识')),
                ('deceased_date', models.DateTimeField(verbose_name='死亡日期')),
                ('deceased_place', models.CharField(max_length=100, verbose_name='死亡地点')),
                ('deceased_reason', models.CharField(max_length=255, verbose_name='死亡原因')),
                ('deceased_contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('deceased_contact_phone', models.CharField(max_length=20, verbose_name='联系人电话')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '死亡户信息',
                'verbose_name_plural': '死亡户信息',
                'db_table': 'deceased',
            },
        ),
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bungalow_number', models.CharField(max_length=50, verbose_name='平房号')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.hutong', verbose_name='胡同')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='居民')),
            ],
            options={
                'verbose_name': '平房信息',
                'verbose_name_plural': '平房信息',
                'db_table': 'bungalow',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.IntegerField(verbose_name='楼房号')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.house', verbose_name='户号')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='居民')),
            ],
            options={
                'verbose_name': '楼房信息',
                'verbose_name_plural': '楼房信息',
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_date', models.DateTimeField(verbose_name='认证日期')),
                ('bank_account_number', models.CharField(max_length=50, unique=True, verbose_name='银行卡号（唯一）')),
                ('bank_account_name', models.CharField(max_length=100, verbose_name='银行卡账户名称')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(db_column='resident_id', on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '特扶户信息',
                'verbose_name_plural': '特扶户信息',
                'db_table': 'special_needs',
            },
        ),
        migrations.CreateModel(
            name='SpecialObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(choices=[(0, '信访'), (1, '新疆'), (2, '西藏')], verbose_name='对象类型')),
                ('object_name', models.CharField(max_length=100, verbose_name='对象姓名')),
                ('object_contact_phone', models.CharField(max_length=20, verbose_name='对象联系电话')),
                ('object_address', models.CharField(max_length=255, verbose_name='对象住址')),
                ('object_responsible_name', models.CharField(max_length=100, verbose_name='负责人姓名')),
                ('object_responsible_phone', models.CharField(max_length=20, verbose_name='负责人联系电话')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resident', models.ForeignKey(db_column='resident_id', on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='居民ID')),
            ],
            options={
                'verbose_name': '重点对象信息',
                'verbose_name_plural': '重点对象信息',
                'db_table': 'special_objects',
            },
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['name'], name='residents_name_a07220_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['ethnicity'], name='residents_ethnici_e1bf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['political_affiliation'], name='residents_politic_78f2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['population_type'], name='residents_populat_f6f260_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['residential_type'], name='residents_residen_946c17_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['marital_status'], name='residents_marital_ce8227_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['education_level'], name='residents_educati_19f213_idx'),
        ),
        migrations.AddIndex(
            model_name='lowincome',
            index=models.Index(fields=['resident_id'], name='idx_low_income_resident_id'),
        ),
        migrations.AddIndex(
            model_name='fiveguarantees',
            index=models.Index(fields=['resident_id'], name='idx_five_guar_resident_id'),
        ),
        migrations.AddIndex(
            model_name='disabled',
            index=models.Index(fields=['resident_id'], name='idx_disabled_resident_id'),
        ),
        migrations.AddIndex(
            model_name='deceased',
            index=models.Index(fields=['resident_id'], name='idx_deceased_resident_id'),
        ),
        migrations.AddIndex(
            model_name='bungalow',
            index=models.Index(fields=['resident', 'bungalow_number'], name='idx_bungalow_resident_number'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['resident', 'house_number'], name='idx_resident_house_number'),
        ),
        migrations.AddIndex(
            model_name='specialneeds',
            index=models.Index(fields=['resident_id'], name='idx_special_needs_resident_id'),
        ),
        migrations.AddIndex(
            model_name='specialobjects',
            index=models.Index(fields=['resident_id'], name='idx_special_obj_resident_id'),
        ),
    ]
