# Generated by Django 5.2.7 on 2025-10-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, unique=True, verbose_name='物业名称')),
                ('property_address', models.CharField(max_length=255, verbose_name='物业地址')),
                ('property_owner', models.CharField(max_length=255, verbose_name='物业负责人')),
                ('property_contact_phone', models.CharField(max_length=20, verbose_name='物业联系电话')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '物业信息',
                'verbose_name_plural': '物业信息',
                'db_table': 'properties',
                'indexes': [models.Index(fields=['property_name'], name='idx_property_name'), models.Index(fields=['property_owner'], name='idx_property_owner'), models.Index(fields=['property_contact_phone'], name='idx_property_contact_phone')],
            },
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('community', models.OneToOneField(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, to='address.community', verbose_name='所属小区ID')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='物业ID')),
            ],
            options={
                'verbose_name': '物业经理信息',
                'verbose_name_plural': '物业经理信息',
                'db_table': 'property_manager',
                'indexes': [models.Index(fields=['property', 'community'], name='idx_property_community')],
            },
        ),
    ]
