# Generated by Django 5.2.7 on 2025-10-17 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255, unique=True, verbose_name='小区名称')),
                ('community_number', models.CharField(max_length=50, verbose_name='小区号')),
                ('has_property', models.BooleanField(default=False, verbose_name='是否有物业')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '小区信息',
                'verbose_name_plural': '小区信息',
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveSmallIntegerField(verbose_name='楼栋号')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.community', verbose_name='小区')),
            ],
            options={
                'verbose_name': '楼栋信息',
                'verbose_name_plural': '楼栋信息',
                'db_table': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='组别唯一标识')),
                ('group_number', models.CharField(max_length=50, unique=True, verbose_name='组别号')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '组别',
                'verbose_name_plural': '组别',
                'db_table': 'groups',
                'indexes': [models.Index(fields=['group_number'], name='idx_group_number')],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.group', verbose_name='所属组别'),
        ),
        migrations.CreateModel(
            name='Hutong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='胡同唯一标识')),
                ('hutong_name', models.CharField(max_length=255, unique=True, verbose_name='胡同名称')),
                ('hutong_number', models.CharField(max_length=50, verbose_name='胡同号')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.group', verbose_name='所属组别')),
            ],
            options={
                'verbose_name': '胡同',
                'verbose_name_plural': '胡同',
                'db_table': 'hutong',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100, unique=True, verbose_name='街道名称')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '街道信息',
                'verbose_name_plural': '街道信息',
                'db_table': 'street',
                'indexes': [models.Index(fields=['street_name'], name='idx_street_name')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.SmallIntegerField(verbose_name='单元号')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.apartment', verbose_name='楼栋')),
            ],
            options={
                'verbose_name': '单元信息',
                'verbose_name_plural': '单元信息',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20, verbose_name='户号')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登记日期')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.unit', verbose_name='单元')),
            ],
            options={
                'verbose_name': '户号信息',
                'verbose_name_plural': '户号信息',
                'db_table': 'house',
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['community', 'apartment_number'], name='idx_apartment_community_number'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_name'], name='idx_community_name'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['group'], name='idx_community_group'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['has_property'], name='idx_community_has_property'),
        ),
        migrations.AddIndex(
            model_name='hutong',
            index=models.Index(fields=['hutong_name'], name='idx_hutong_name'),
        ),
        migrations.AddIndex(
            model_name='hutong',
            index=models.Index(fields=['group'], name='idx_hutong_group'),
        ),
        migrations.AddIndex(
            model_name='hutong',
            index=models.Index(fields=['hutong_number'], name='idx_hutong_number'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_number'], name='idx_unit_number'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['apartment'], name='idx_unit_apartment'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['unit'], name='idx_house_unit'),
        ),
    ]
